# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-json
  - id: check-xml
  - id: pretty-format-json
    args:
    - --autofix
    - --indent=4
- repo: https://github.com/gherynos/pre-commit-java
  rev: v0.4.0
  hooks:
  - id: checkstyle
    args: [-c, /google_checks.xml]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-java
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/collective/zpretty
  rev: 3.1.0
  hooks:
  - id: zpretty
